UI_TEXT = {
    "en": {
        "language_label": "Language / Bahasa",
        "main_navigation": "Main Navigation",
        "hello_user": "Hello, **{name}**!",
        "main_page_label": "Choose Page:",
        "page.start": "Start",
        "page.dashboard": "Dashboard",
        "page.area_analysis": "Area Analysis",
        "page.cost_analysis": "Cost Analysis",
        "page.database": "Database",
        "page.summary": "Summary",
        "page.archive": "Archive",
        "current_study": "Current study",
        "save_current_study": "Save Current Study",
        "current_linked_study_saved": "Current linked study saved: {name}",
        "working_copy_saved_archive_hint": (
            "Working copy saved. To create or link an archive, use Archive > Online Backup > Save."
        ),
        "show_detailed_control": "Show detailed control.",
        "project_list": "Project List",
        "active_component": "Active Component:",
        "move_up": "Move Up",
        "move_down": "Move Down",
        "project_order_saved": "Project order saved to cloud.",
        "project_order_save_failed": (
            "Project order changed locally, but cloud save failed. Do not log out yet."
        ),
        "add": "Add",
        "edit": "Edit",
        "delete": "Delete",
        "add_component": "Add Component",
        "edit_component": "Edit Component",
        "component_name": "Component Name",
        "component_name_placeholder": "e.g. Apartment Tower A",
        "component_type": "Component Type",
        "create": "Create",
        "cancel": "Cancel",
        "save": "Save",
        "component_name_empty": "Component name cannot be empty.",
        "component_name_duplicate": "Project name already exists.",
        "component_name_duplicate_unique": "Component name already exists. Use a unique name.",
        "component_added_saved": "Component added and saved to cloud.",
        "component_added_save_failed": "Component added locally, but cloud save failed. Do not log out yet.",
        "component_saved": "Component saved to cloud.",
        "component_save_failed": "Component changed locally, but cloud save failed. Do not log out yet.",
        "hidden_project_type_note": (
            "This project uses a hidden project type. It is still valid, but hidden from new project creation."
        ),
        "unknown_project_type_note": (
            "This project uses an unknown project type. It will be preserved, but fallback database defaults may be used."
        ),
        "delete_selected_components": "Delete selected components?",
        "delete_selected_components_caption": "Select one or more components below, then confirm delete.",
        "one_component_must_remain": "At least one component must remain.",
        "select_components_to_delete": "Select components to delete:",
        "selected_components_remaining": "{selected} selected. {remaining} component(s) will remain.",
        "cannot_delete_all_components": "You cannot delete all components. At least one must remain.",
        "confirm": "Confirm",
        "component_deleted_saved": "Component deleted and saved to cloud.",
        "component_deleted_save_failed": "Component deleted locally, but cloud save failed. Do not log out yet.",
        "logout": "Logout",
        "back_to_app": "Back to App",
        "debug": "Debug",
        "dashboard.title": "Dashboard",
        "dashboard.caption": "Read-only study overview. This page does not change saved data.",
        "dashboard.no_projects": "No projects found in this study.",
        "dashboard.metric_project_count": "Project Count",
        "dashboard.metric_total_budget": "Total Budget",
        "dashboard.metric_total_gba": "Total GBA",
        "dashboard.metric_avg_rp_gba": "Avg Rp/m2 GBA",
        "dashboard.metric_total_gfa": "Total GFA",
        "dashboard.metric_total_sgfa": "Total SGFA",
        "dashboard.metric_total_nfa": "Total NFA",
        "dashboard.metric_warning_count": "Warning Count",
        "dashboard.budget_by_project": "Budget by Project",
        "dashboard.no_budget_data": "No budget data available yet.",
        "dashboard.study_health": "Study Health",
        "dashboard.no_warnings": "No dashboard warnings detected.",
        "dashboard.warnings_detected": "{count} warning(s) detected.",
        "dashboard.project_comparison": "Project Comparison",
        "dashboard.area_ratios": "Area Ratios",
        "dashboard.no_area_ratio_data": "No area ratio data available yet.",
        "dashboard.project": "Project",
        "dashboard.type": "Type",
        "dashboard.rooms_units": "Rooms / Units",
        "dashboard.budget": "Budget",
        "dashboard.status": "Status",
        "dashboard.warning": "Warning",
        "dashboard.ok": "OK",
        "dashboard.missing_gba": "Missing GBA",
        "dashboard.missing_gfa": "Missing GFA",
        "dashboard.missing_sgfa": "Missing SGFA",
        "dashboard.missing_nfa": "Missing NFA",
        "dashboard.missing_budget": "Missing Budget",
        "dashboard.missing_rooms": "Missing Rooms",
        "summary.title": "Summary",
        "summary.tab_config": "Config",
        "summary.tab_fad": "FAD",
        "summary.tab_recap": "Recap",
        "summary.approval_export_settings": "Approval / Export Settings",
        "summary.prepared_by": "Prepared By",
        "summary.checked_by": "Checked By",
        "summary.header_configuration": "Header Configuration",
        "summary.project_location": "Project Location",
        "summary.project_location_placeholder": "Example: PIK2.D2.",
        "summary.project_name": "Project Name",
        "summary.project_name_placeholder": "Example: GINZA.MIDTOWN",
        "summary.option_number": "Option Number",
        "summary.option_number_placeholder": "Example: 2",
        "summary.revision_number": "Revision Number",
        "summary.revision_number_placeholder": "Example: 0",
        "summary.drawing_date": "Drawing Date",
        "summary.updated_date": "Updated Date",
        "summary.created_date": "Created Date",
        "summary.header_preview": "Header Preview",
        "summary.assumptions_configuration": "Assumptions Configuration",
        "summary.assumptions_caption": (
            "These assumptions are displayed below the FAD table. Keep the wording aligned with the required report format."
        ),
        "summary.assumption_no": "No.",
        "summary.assumption_description": "Assumption Description",
        "summary.save_change": "Save Change",
        "summary.saved_to_cloud": "Saved to cloud.",
        "summary.cloud_save_failed": "Cloud save failed. Do not log out yet.",
        "summary.fad_title": "Feasibility Analysis Data (FAD)",
        "summary.recap_title": "Comprehensive Recap Matrix (Cost & Ratios)",
        "summary.download_excel": "Download Excel",
        "area.title": "Area Analysis",
        "area.save": "Save",
        "area.save_current_page": "Save current Area page: {page}",
        "area.no_save_action": "No save action for current Area page: {page}",
        "area.gba_setup": "GBA Setup",
        "area.input_mode": "Area Input Mode",
        "area.manual_input_page": "Manual Input Page",
        "area.mode.excel": "Excel",
        "area.mode.manual_input": "Manual Input",
        "area.page.gba_input": "GBA Input",
        "area.page.pintu": "Pintu",
        "area.page.eksternal": "Eksternal",
        "area.page.facility_misc": "Facility / Misc",
        "area.page.earthworks": "Earthworks",
        "area.page.structural": "Structural",
        "area.page.foundation": "Foundation",
        "area.page.architectural": "Architectural",
        "area.page.ffe": "FF&E",
        "area.page.mep": "MEP",
        "area.page.utility": "Utility",
        "area.page.consultancy": "Consultancy",
        "area.excel_page_title": "Area Analysis (Excel)",
        "area.manual_input_title": "Manual Input",
        "area.doors_page_title": "Area Analysis (Doors)",
        "area.external_page_title": "Area Analysis (External Works)",
        "area.facility_misc_page_title": "Area Analysis (Facility / Misc)",
        "area.earthworks_page_title": "Area Analysis (Earthworks)",
        "area.foundation_page_title": "Area Analysis (Foundation)",
        "area.structural_page_title": "Area Analysis (Structural)",
        "area.architectural_page_title": "Area Analysis (Architectural)",
        "area.consultancy_page_title": "Area Analysis (Consultancy)",
        "area.ffe_page_title": "Area Analysis (FF&E)",
        "area.mep_page_title": "Area Analysis (MEP)",
        "area.utility_page_title": "Area Analysis (Utility)",
        "area.gba.basements_lg": "Basements / LG",
        "area.gba.basements_lg_help": "1 = LG, 2 = B1, 3 = B2, etc",
        "area.gba.floors": "Floors",
        "area.gba.land_area": "Luas Tanah (m2)",
        "area.gba.caption": "Edit here first. Calculations and cost sync will not update until you click Save.",
        "area.gba.generate_table": "Generate Table",
        "area.gba.reset_draft": "Reset Draft",
        "area.gba.generated": "New area table generated and committed.",
        "area.gba.generate_save_failed": (
            "Cloud save failed. Generated area table changed locally, but was not saved. Do not log out yet."
        ),
        "area.gba.draft_reset": "Draft reset to last applied table.",
        "area.gba.input_mode": "Area Input Mode",
        "area.gba.input_mode_detailed": "Detailed Category",
        "area.gba.input_mode_consultant": "Consultant Summary",
        "area.gba.input_mode_help": (
            "Detailed Category = input each physical category. "
            "Consultant Summary = input cumulative NFA, SGFA, and GFA per floor."
        ),
        "area.gba.space_type": "Space Type",
        "area.gba.height": "Height (m)",
        "area.gba.height_help": "Vertical height from one finished floor level to the next.",
        "area.gba.typical_unit": "Typical Unit",
        "area.gba.typical_unit_help": "Number of typical units on this floor. This is a count, not an area.",
        "area.gba.gfa_help": "Consultant mode: cumulative GFA. Converted to Stair, MEP, Etc = GFA - SGFA.",
        "area.gba.sgfa_help": "Consultant mode: cumulative SGFA. Converted to Koridor/Lobby = SGFA - NFA.",
        "area.gba.nfa_help": "Consultant mode: NFA. Converted to Unit Area.",
        "area.gba.saved_to_cloud": "Saved to cloud.",
        "area.gba.cloud_save_failed": "Cloud save failed. Do not log out yet.",
        "area_excel_form_title": "Excel Form",
        "area_excel_download_title": "Download Area Calculator Excel Form",
        "area_excel_download_button": "Download",
        "area_excel_upload_title": "Upload Area Calculator Excel Form",
        "area_excel_upload_help": "Upload the Excel form generated from this app.",
        "area_excel_import_button": "Import Excel to Area Calculator",
        "area_excel_imported_rows": "Imported area rows: {count}",
        "area_excel_import_success": "Excel imported successfully. {count} area rows loaded.",
        "area_excel_import_save_message": "Area Excel Import",
        "area_excel_import_cloud_failed": "Cloud save failed. Imported area data changed locally, but was not saved. Do not log out yet.",
        "area_excel_import_failed": "Excel import failed. Please upload a valid .xlsx file generated from this app.",
        "area_excel_import_failed_detail": "Excel import failed: {error}",
        "cost_input_proposals_imported": "Cost Analysis Input proposals imported for review. Cost Analysis was not changed.",
        "cost_input_warnings_title": "Cost Analysis Input warnings",
        "technical_details": "Technical details",
        "dismiss": "Dismiss",
        "summary_key_area_metrics": "Summary of Key Area Metrics",
        "file_information": "File Information:",
        "core_area": "Core Area",
        "opening_external": "Opening / External",
        "review_area_sync": "Review Area Sync",
        "sync_review_caption": "Positive source values can update Cost Analysis inputs. Zero source values are skipped except allowed ratio values.",
        "sync_filter_changed": "Changed",
        "sync_filter_unchanged": "Unchanged",
        "sync_filter_skipped_zero": "Skipped / Zero",
        "sync_filter_all": "All",
        "sync_no_values_group": "No values in this group.",
        "sync_col_group": "Group",
        "sync_col_value": "Value",
        "sync_col_current_value": "Current Value",
        "sync_col_source_value": "Source Value",
        "sync_col_difference": "Difference",
        "sync_col_source_origin": "Source Origin",
        "sync_col_status": "Status",
        "sync_source_area_analysis": "Area Analysis",
        "sync_source_excel_proposed": "Excel Proposed Value",
        "sync_status_changed": "Changed",
        "sync_status_unchanged": "Unchanged",
        "sync_status_skipped_zero": "Skipped - zero source",
        "sync_status_skipped_negative": "Skipped - negative source",
        "sync_status_missing_target": "Missing target",
        "sync_apply_button": "Apply Sync",
        "sync_cancel_button": "Cancel",
        "sync_apply_success": "Area metrics, opening/external quantities, and detail-derived rates applied to Cost Analysis.",
        "sync_apply_cloud_failed": "Area Analysis values were applied locally, but cloud save failed. Do not log out yet.",
        "cost_title": "Cost Analysis",
        "cost_sync_button": "Sync",
        "cost_sync_help": "Review Area Analysis values before syncing",
        "cost_save_button": "Save",
        "cost_save_help": "Save Cost Analysis",
        "cost_save_success": "Saved to cloud.",
        "cost_save_cloud_failed": "Cloud save failed. Do not log out yet.",
        "cost_prelim_label": "Preliminaries %",
        "cost_prelim_help": "Applied to Construction Subtotal.",
        "cost_conting_label": "Contingencies %",
        "cost_conting_help": "Applied to Construction Subtotal + Preliminaries.",
        "cost_tab_size": "1. Size",
        "cost_tab_ratio": "2. Ratio",
        "cost_tab_soft_costs": "3. Soft Costs",
        "cost_tab_rates": "4. Rates",
        "cost_tab_custom_items": "5. Additional Items",
        "cost_tab_results": "6. Results",
        "cost_tab_proof": "7. Proof / Check",
        "cost_section_project_size": "Project Size",
        "cost_section_size": "Size",
        "cost_section_architecture": "Architecture",
        "cost_section_interior": "Interior",
        "cost_section_exterior": "Exterior",
        "cost_section_doors": "Doors",
        "cost_section_sanitary": "Sanitary",
        "cost_section_toilet_unit": "Toilet Unit",
        "cost_section_public_toilet": "Public Toilet",
        "cost_section_prayer_room": "Prayer Room",
        "cost_section_facilities": "Facilities",
        "cost_section_ffe_others": "FF&E Others",
        "cost_section_facade_ratio": "Facade Ratio (%)",
        "cost_section_waste_skirting": "Waste & Skirting (%)",
        "cost_section_flooring_ratio": "Flooring Ratio (%)",
        "cost_no_values_available": "No values available.",
        "cost_no_changes_apply": "No changes to apply.",
        "cost_detail_rate_review_title": "Detail-Derived Rate Review",
        "cost_detail_rate_review_caption": "Review only. Detail-derived rates are not applied to Cost Analysis automatically.",
        "cost_detail_col_current_rate": "Current Cost Rate",
        "cost_detail_col_derived_rate": "Detail-Derived Rate",
        "cost_detail_col_difference_unit": "Difference / Unit",
        "cost_detail_col_detail_total": "Detail Total",
        "cost_detail_col_current_total": "Current Total",
        "cost_detail_col_difference_total": "Difference Total",
        "cost_detail_current_rate_label": "Current Rate",
        "cost_detail_derived_rate_label": "Derived Rate",
        "cost_detail_difference_label": "Difference",
        "cost_detail_status_label": "Status",
        "cost_detail_apply_earthworks": "Apply Earthworks Detail Rate",
        "cost_detail_apply_foundation": "Apply Foundation Detail Rate",
        "cost_detail_apply_structural": "Apply Structural Detail Rate",
        "cost_detail_apply_architectural": "Apply Architectural Detail Rate",
        "cost_detail_apply_consultancy": "Apply Consultancy Detail Rate",
        "cost_detail_apply_ffe": "Apply FF&E Detail Rate",
        "cost_detail_apply_mep": "Apply MEP Detail Rate",
        "cost_detail_apply_utility": "Apply Utility Detail Rate",
        "cost_detail_apply_success": "{section} detail rate applied.",
        "cost_detail_apply_cloud_failed": "{section} detail rate was applied locally, but cloud save failed. Do not log out yet.",
        "cost_detail_apply_no_rate": "No valid detail-derived rate is available for {section}.",
        "cost_detail_diff_warning": "{section} detail-derived rate differs from the current Cost Analysis {section} Rate. Cost Analysis has not been updated automatically.",
        "cost_detail_info_title": "{section} Detail-Derived Rate Review",
        "admin.feasibility_study": "Feasibility Study",
        "admin.loaded_file_ready": "**{name}** is currently loaded (You can start calculating your project)",
        "admin.previous_page": "Previous Page",
        "admin.welcome_start": (
            "**Welcome to Project Feasibility Study - Agung Sedayu Group**\n\n"
            "To start calculating, first create a new project by clicking the button below."
        ),
        "admin.create_new_study": "Create New Study",
        "admin.create_new_feasibility_study": "Create New Feasibility Study",
        "admin.create_study_caption": "Enter a study name. A new default project will be created automatically.",
        "admin.back": "Back",
        "admin.feasibility_study_name": "Feasibility Study Name",
        "admin.study_name_placeholder": "e.g. Project X - Option 1 - Rev 0",
        "admin.enter_study_name": "Please enter feasibility study name.",
        "admin.duplicate_study_name": "A study with this name already exists. Use a different name.",
        "admin.initial_archive_failed": (
            "Study **{name}** was created in the current session, but the initial archive record could not be created."
        ),
        "admin.study_created_saved": "Study **{name}** created and saved to archive.",
        "admin.study_saved": "Study **{name}** saved to archive.",
        "admin.save_current_page_first": "Save the current page first if needed.",
        "admin.no_saved_studies": "No saved feasibility studies yet.",
        "admin.currently_loaded_file": "Currently loaded file",
        "admin.saved_at": "Saved: {time}{active}",
        "admin.saved_file": "Saved file{active}",
        "admin.load": "Load",
        "admin.loaded_file": "Loaded **{name}**.",
        "admin.page_count": "Page {current} of {total}",
        "admin.archive": "Archive",
        "admin.online_backup": "Online Backup",
        "admin.offline_backup": "Offline Backup",
        "admin.notes": "Notes",
        "admin.project_history": "Project History",
        "admin.working_copy": "Working copy: {name}",
        "admin.legacy_restore_points": "Legacy in-project restore points detected. New restore points are stored externally.",
        "admin.save_draft": "Save Draft",
        "admin.draft_saved": "Draft saved to cloud.",
        "admin.draft_save_failed": "Draft changed locally, but cloud save failed. Do not log out yet.",
        "admin.create_restore_point": "Create Restore Point",
        "admin.restore_points_used": "{used} of {limit} restore points used.",
        "admin.restore_point_note": "Restore point note",
        "admin.restore_point_note_placeholder": "e.g. QS review before VE changes",
        "admin.restore_point_limit": "Restore point limit reached. Delete old restore points first to create another one.",
        "admin.restore_point_created": "Restore point {label} created.",
        "admin.no_restore_points": "No restore points yet. Create one before making risky changes.",
        "admin.restore_points": "Restore Points",
        "admin.restore_selected_restore_point": "Restore Selected Restore Point",
        "admin.select_restore_point": "Select restore point",
        "admin.restore_confirm": "I understand this will replace the current working copy.",
        "admin.restore_saved": "Restore selected restore point saved to working copy.",
        "admin.restore_save_failed": "Restore point restored locally, but cloud save failed. Do not log out yet.",
        "admin.restore_failed": "Selected restore point could not be restored.",
        "admin.compare_current_restore": "Compare Current vs Restore Point",
        "admin.select_restore_compare": "Select restore point to compare",
        "admin.no_restorable_snapshot": "Selected restore point has no restorable snapshot.",
        "admin.delete_restore_point": "Delete Restore Point",
        "admin.select_restore_delete": "Select restore point to delete",
        "admin.delete_restore_confirm": "I understand this will permanently delete only this restore point.",
        "admin.restore_point_deleted": "Restore point deleted.",
        "admin.label": "Label",
        "admin.note": "Note",
        "admin.created_at": "Created At",
        "admin.created_by": "Created By",
        "admin.current": "Current",
        "admin.restore_point": "Restore Point",
        "admin.change": "Change",
        "admin.write_note": "Write a note",
        "admin.note_placeholder": "Example: Check area lanskap and rate later...",
        "admin.add_note": "Add Note",
        "admin.write_note_first": "Please write a note first.",
        "admin.add_simple_note": "Add Simple Note",
        "admin.saved_notes": "Saved Notes",
        "admin.no_notes": "No notes yet.",
        "admin.delete_simple_note": "Delete Simple Note",
        "admin.name": "Name",
        "admin.project_name_required": "Please enter Project name.",
        "admin.save": "Save",
        "admin.load_file": "Load File",
        "admin.no_saved_projects": "No saved projects yet.",
        "admin.showing_saved_files": "Showing {start}-{end} of {total} saved files",
        "admin.rename": "Rename",
        "admin.new_file_name": "New file name",
        "admin.save_name": "Save Name",
        "admin.file_renamed": "File renamed.",
        "admin.delete_file_confirm": "Delete **{name}**?",
        "admin.archived_file_removed": "This archived file will be removed from the library.",
        "admin.file_deleted": "File deleted.",
        "admin.previous": "Previous",
        "admin.next": "Next",
        },
    "id": {
        "language_label": "Language / Bahasa",
        "main_navigation": "Navigasi Utama",
        "hello_user": "Halo, **{name}**!",
        "main_page_label": "Pilih Halaman:",
        "page.start": "Start",
        "page.dashboard": "Dashboard",
        "page.area_analysis": "Analisis Area",
        "page.cost_analysis": "Analisis Biaya",
        "page.database": "Database",
        "page.summary": "Ringkasan",
        "page.archive": "Arsip",
        "current_study": "Studi saat ini",
        "save_current_study": "Simpan Studi Saat Ini",
        "current_linked_study_saved": "Studi tertaut berhasil disimpan: {name}",
        "working_copy_saved_archive_hint": (
            "Working copy berhasil disimpan. Untuk membuat atau menautkan arsip, gunakan Archive > Online Backup > Save."
        ),
        "show_detailed_control": "Tampilkan kontrol detail.",
        "project_list": "Daftar Proyek",
        "active_component": "Komponen Aktif:",
        "move_up": "Pindah ke Atas",
        "move_down": "Pindah ke Bawah",
        "project_order_saved": "Urutan proyek berhasil disimpan ke cloud.",
        "project_order_save_failed": (
            "Urutan proyek berubah secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu."
        ),
        "add": "Tambah",
        "edit": "Edit",
        "delete": "Hapus",
        "add_component": "Tambah Komponen",
        "edit_component": "Edit Komponen",
        "component_name": "Nama Komponen",
        "component_name_placeholder": "contoh: Apartment Tower A",
        "component_type": "Tipe Komponen",
        "create": "Buat",
        "cancel": "Batal",
        "save": "Simpan",
        "component_name_empty": "Nama komponen tidak boleh kosong.",
        "component_name_duplicate": "Nama proyek sudah ada.",
        "component_name_duplicate_unique": "Nama komponen sudah ada. Gunakan nama yang unik.",
        "component_added_saved": "Komponen berhasil ditambahkan dan disimpan ke cloud.",
        "component_added_save_failed": "Komponen ditambahkan secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "component_saved": "Komponen berhasil disimpan ke cloud.",
        "component_save_failed": "Komponen berubah secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "hidden_project_type_note": (
            "Proyek ini memakai tipe proyek tersembunyi. Nilainya tetap valid, tetapi tersembunyi dari pembuatan proyek baru."
        ),
        "unknown_project_type_note": (
            "Proyek ini memakai tipe proyek tidak dikenal. Nilainya akan dipertahankan, tetapi default database cadangan mungkin dipakai."
        ),
        "delete_selected_components": "Hapus komponen yang dipilih?",
        "delete_selected_components_caption": "Pilih satu atau beberapa komponen di bawah, lalu konfirmasi hapus.",
        "one_component_must_remain": "Minimal satu komponen harus tersisa.",
        "select_components_to_delete": "Pilih komponen untuk dihapus:",
        "selected_components_remaining": "{selected} dipilih. {remaining} komponen akan tersisa.",
        "cannot_delete_all_components": "Anda tidak dapat menghapus semua komponen. Minimal satu komponen harus tersisa.",
        "confirm": "Konfirmasi",
        "component_deleted_saved": "Komponen berhasil dihapus dan disimpan ke cloud.",
        "component_deleted_save_failed": "Komponen dihapus secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "logout": "Logout",
        "back_to_app": "Kembali ke App",
        "debug": "Debug",
        "dashboard.title": "Dashboard",
        "dashboard.caption": "Ringkasan studi hanya-baca. Halaman ini tidak mengubah data tersimpan.",
        "dashboard.no_projects": "Tidak ada proyek dalam studi ini.",
        "dashboard.metric_project_count": "Jumlah Proyek",
        "dashboard.metric_total_budget": "Total Anggaran",
        "dashboard.metric_total_gba": "Total GBA",
        "dashboard.metric_avg_rp_gba": "Rata-rata Rp/m2 GBA",
        "dashboard.metric_total_gfa": "Total GFA",
        "dashboard.metric_total_sgfa": "Total SGFA",
        "dashboard.metric_total_nfa": "Total NFA",
        "dashboard.metric_warning_count": "Jumlah Peringatan",
        "dashboard.budget_by_project": "Anggaran per Proyek",
        "dashboard.no_budget_data": "Belum ada data anggaran.",
        "dashboard.study_health": "Kesehatan Studi",
        "dashboard.no_warnings": "Tidak ada peringatan dashboard.",
        "dashboard.warnings_detected": "{count} peringatan terdeteksi.",
        "dashboard.project_comparison": "Perbandingan Proyek",
        "dashboard.area_ratios": "Rasio Area",
        "dashboard.no_area_ratio_data": "Belum ada data rasio area.",
        "dashboard.project": "Proyek",
        "dashboard.type": "Tipe",
        "dashboard.rooms_units": "Kamar / Unit",
        "dashboard.budget": "Anggaran",
        "dashboard.status": "Status",
        "dashboard.warning": "Peringatan",
        "dashboard.ok": "OK",
        "dashboard.missing_gba": "GBA belum diisi",
        "dashboard.missing_gfa": "GFA belum diisi",
        "dashboard.missing_sgfa": "SGFA belum diisi",
        "dashboard.missing_nfa": "NFA belum diisi",
        "dashboard.missing_budget": "Anggaran belum diisi",
        "dashboard.missing_rooms": "Kamar/unit belum diisi",
        "summary.title": "Ringkasan",
        "summary.tab_config": "Konfigurasi",
        "summary.tab_fad": "FAD",
        "summary.tab_recap": "Recap",
        "summary.approval_export_settings": "Pengaturan Persetujuan / Ekspor",
        "summary.prepared_by": "Disiapkan Oleh",
        "summary.checked_by": "Diperiksa Oleh",
        "summary.header_configuration": "Konfigurasi Header",
        "summary.project_location": "Lokasi Proyek",
        "summary.project_location_placeholder": "Contoh: PIK2.D2.",
        "summary.project_name": "Nama Proyek",
        "summary.project_name_placeholder": "Contoh: GINZA.MIDTOWN",
        "summary.option_number": "Nomor Opsi",
        "summary.option_number_placeholder": "Contoh: 2",
        "summary.revision_number": "Nomor Revisi",
        "summary.revision_number_placeholder": "Contoh: 0",
        "summary.drawing_date": "Tanggal Gambar",
        "summary.updated_date": "Tanggal Diperbarui",
        "summary.created_date": "Tanggal Dibuat",
        "summary.header_preview": "Pratinjau Header",
        "summary.assumptions_configuration": "Konfigurasi Asumsi",
        "summary.assumptions_caption": (
            "Asumsi ini ditampilkan di bawah tabel FAD. Jaga wording tetap sesuai format laporan."
        ),
        "summary.assumption_no": "No.",
        "summary.assumption_description": "Deskripsi Asumsi",
        "summary.save_change": "Simpan Perubahan",
        "summary.saved_to_cloud": "Berhasil disimpan ke cloud.",
        "summary.cloud_save_failed": "Gagal menyimpan ke cloud. Jangan logout dulu.",
        "summary.fad_title": "Data Analisis Kelayakan (FAD)",
        "summary.recap_title": "Matriks Recap Komprehensif (Biaya & Rasio)",
        "summary.download_excel": "Unduh Excel",
        "area.title": "Analisis Area",
        "area.save": "Simpan",
        "area.save_current_page": "Simpan halaman Area saat ini: {page}",
        "area.no_save_action": "Tidak ada aksi simpan untuk halaman Area saat ini: {page}",
        "area.gba_setup": "Pengaturan GBA",
        "area.input_mode": "Mode Input Area",
        "area.manual_input_page": "Halaman Input Manual",
        "area.mode.excel": "Excel",
        "area.mode.manual_input": "Input Manual",
        "area.page.gba_input": "Input GBA",
        "area.page.pintu": "Pintu",
        "area.page.eksternal": "Eksternal",
        "area.page.facility_misc": "Facility / Misc",
        "area.page.earthworks": "Earthworks",
        "area.page.structural": "Structural",
        "area.page.foundation": "Foundation",
        "area.page.architectural": "Architectural",
        "area.page.ffe": "FF&E",
        "area.page.mep": "MEP",
        "area.page.utility": "Utility",
        "area.page.consultancy": "Consultancy",
        "area.excel_page_title": "Analisis Area (Excel)",
        "area.manual_input_title": "Input Manual",
        "area.doors_page_title": "Analisis Area (Doors)",
        "area.external_page_title": "Analisis Area (External Works)",
        "area.facility_misc_page_title": "Analisis Area (Facility / Misc)",
        "area.earthworks_page_title": "Analisis Area (Earthworks)",
        "area.foundation_page_title": "Analisis Area (Foundation)",
        "area.structural_page_title": "Analisis Area (Structural)",
        "area.architectural_page_title": "Analisis Area (Architectural)",
        "area.consultancy_page_title": "Analisis Area (Consultancy)",
        "area.ffe_page_title": "Analisis Area (FF&E)",
        "area.mep_page_title": "Analisis Area (MEP)",
        "area.utility_page_title": "Analisis Area (Utility)",
        "area.gba.basements_lg": "Basement / LG",
        "area.gba.basements_lg_help": "1 = LG, 2 = B1, 3 = B2, dst.",
        "area.gba.floors": "Jumlah Lantai",
        "area.gba.land_area": "Luas Tanah (m2)",
        "area.gba.caption": "Edit di sini terlebih dahulu. Kalkulasi dan sinkron biaya belum berubah sampai Anda klik Simpan.",
        "area.gba.generate_table": "Buat Tabel",
        "area.gba.reset_draft": "Reset Draft",
        "area.gba.generated": "Tabel area baru berhasil dibuat dan diterapkan.",
        "area.gba.generate_save_failed": (
            "Gagal menyimpan ke cloud. Tabel area baru berubah secara lokal, tetapi belum tersimpan. Jangan logout dulu."
        ),
        "area.gba.draft_reset": "Draft dikembalikan ke tabel terakhir yang diterapkan.",
        "area.gba.input_mode": "Mode Input Area",
        "area.gba.input_mode_detailed": "Kategori Detail",
        "area.gba.input_mode_consultant": "Ringkasan Konsultan",
        "area.gba.input_mode_help": (
            "Kategori Detail = input setiap kategori fisik. "
            "Ringkasan Konsultan = input kumulatif NFA, SGFA, dan GFA per lantai."
        ),
        "area.gba.space_type": "Tipe Ruang",
        "area.gba.height": "Tinggi (m)",
        "area.gba.height_help": "Tinggi vertikal dari satu level lantai jadi ke level lantai berikutnya.",
        "area.gba.typical_unit": "Unit Tipikal",
        "area.gba.typical_unit_help": "Jumlah unit tipikal pada lantai ini. Ini adalah jumlah unit, bukan luas.",
        "area.gba.gfa_help": "Mode konsultan: GFA kumulatif. Dikonversi ke Stair, MEP, Etc = GFA - SGFA.",
        "area.gba.sgfa_help": "Mode konsultan: SGFA kumulatif. Dikonversi ke Koridor/Lobby = SGFA - NFA.",
        "area.gba.nfa_help": "Mode konsultan: NFA. Dikonversi ke Unit Area.",
        "area.gba.saved_to_cloud": "Berhasil disimpan ke cloud.",
        "area.gba.cloud_save_failed": "Gagal menyimpan ke cloud. Jangan logout dulu.",
        "area_excel_form_title": "Form Excel",
        "area_excel_download_title": "Unduh Form Excel Kalkulator Area",
        "area_excel_download_button": "Unduh",
        "area_excel_upload_title": "Unggah Form Excel Kalkulator Area",
        "area_excel_upload_help": "Unggah form Excel yang dibuat dari aplikasi ini.",
        "area_excel_import_button": "Impor Excel ke Kalkulator Area",
        "area_excel_imported_rows": "Baris area yang diimpor: {count}",
        "area_excel_import_success": "Excel berhasil diimpor. {count} baris area dimuat.",
        "area_excel_import_save_message": "Impor Excel Area",
        "area_excel_import_cloud_failed": "Gagal menyimpan ke cloud. Data area yang diimpor berubah secara lokal, tetapi belum tersimpan. Jangan logout dulu.",
        "area_excel_import_failed": "Impor Excel gagal. Unggah file .xlsx valid yang dibuat dari aplikasi ini.",
        "area_excel_import_failed_detail": "Impor Excel gagal: {error}",
        "cost_input_proposals_imported": "Proposal Cost Analysis Input berhasil diimpor untuk ditinjau. Cost Analysis belum berubah.",
        "cost_input_warnings_title": "Peringatan Cost Analysis Input",
        "technical_details": "Detail teknis",
        "dismiss": "Tutup",
        "summary_key_area_metrics": "Ringkasan Metrik Area Utama",
        "file_information": "Informasi File:",
        "core_area": "Area Inti",
        "opening_external": "Opening / Eksternal",
        "review_area_sync": "Tinjau Sinkron Area",
        "sync_review_caption": "Nilai sumber positif dapat memperbarui input Cost Analysis. Nilai nol dilewati kecuali nilai rasio yang diizinkan.",
        "sync_filter_changed": "Berubah",
        "sync_filter_unchanged": "Tidak Berubah",
        "sync_filter_skipped_zero": "Dilewati / Nol",
        "sync_filter_all": "Semua",
        "sync_no_values_group": "Tidak ada nilai dalam grup ini.",
        "sync_col_group": "Grup",
        "sync_col_value": "Nilai",
        "sync_col_current_value": "Nilai Saat Ini",
        "sync_col_source_value": "Nilai Sumber",
        "sync_col_difference": "Selisih",
        "sync_col_source_origin": "Asal Sumber",
        "sync_col_status": "Status",
        "sync_source_area_analysis": "Analisis Area",
        "sync_source_excel_proposed": "Proposal Excel",
        "sync_status_changed": "Berubah",
        "sync_status_unchanged": "Tidak Berubah",
        "sync_status_skipped_zero": "Dilewati - sumber nol",
        "sync_status_skipped_negative": "Dilewati - sumber negatif",
        "sync_status_missing_target": "Target tidak ditemukan",
        "sync_apply_button": "Terapkan Sinkron",
        "sync_cancel_button": "Batal",
        "sync_apply_success": "Metrik area, kuantitas opening/eksternal, dan rate dari detail berhasil diterapkan ke Cost Analysis.",
        "sync_apply_cloud_failed": "Nilai Area Analysis diterapkan secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "cost_title": "Analisis Biaya",
        "cost_sync_button": "Sync",
        "cost_sync_help": "Tinjau nilai Area Analysis sebelum sinkronisasi",
        "cost_save_button": "Simpan",
        "cost_save_help": "Simpan Analisis Biaya",
        "cost_save_success": "Tersimpan ke cloud.",
        "cost_save_cloud_failed": "Gagal menyimpan ke cloud. Jangan logout dulu.",
        "cost_prelim_label": "Preliminaries %",
        "cost_prelim_help": "Diterapkan pada Subtotal Konstruksi.",
        "cost_conting_label": "Contingencies %",
        "cost_conting_help": "Diterapkan pada Subtotal Konstruksi + Preliminaries.",
        "cost_tab_size": "1. Ukuran",
        "cost_tab_ratio": "2. Rasio",
        "cost_tab_soft_costs": "3. Soft Costs",
        "cost_tab_rates": "4. Harga",
        "cost_tab_custom_items": "5. Item Tambahan",
        "cost_tab_results": "6. Hasil",
        "cost_tab_proof": "7. Pembuktian",
        "cost_section_project_size": "Ukuran Proyek",
        "cost_section_size": "Ukuran",
        "cost_section_architecture": "Arsitektur",
        "cost_section_interior": "Interior",
        "cost_section_exterior": "Eksterior",
        "cost_section_doors": "Pintu",
        "cost_section_sanitary": "Sanitari",
        "cost_section_toilet_unit": "Unit Toilet",
        "cost_section_public_toilet": "Toilet Umum",
        "cost_section_prayer_room": "Mushola",
        "cost_section_facilities": "Fasilitas",
        "cost_section_ffe_others": "FF&E Lainnya",
        "cost_section_facade_ratio": "Rasio Fasad (%)",
        "cost_section_waste_skirting": "Waste & Skirting (%)",
        "cost_section_flooring_ratio": "Rasio Lantai (%)",
        "cost_no_values_available": "Tidak ada nilai tersedia.",
        "cost_no_changes_apply": "Tidak ada perubahan untuk diterapkan.",
        "cost_detail_rate_review_title": "Tinjauan Harga dari Detail",
        "cost_detail_rate_review_caption": "Hanya untuk ditinjau. Harga dari detail tidak otomatis diterapkan ke Analisis Biaya.",
        "cost_detail_col_current_rate": "Harga Saat Ini",
        "cost_detail_col_derived_rate": "Harga dari Detail",
        "cost_detail_col_difference_unit": "Selisih / Unit",
        "cost_detail_col_detail_total": "Total Detail",
        "cost_detail_col_current_total": "Total Saat Ini",
        "cost_detail_col_difference_total": "Total Selisih",
        "cost_detail_current_rate_label": "Harga Saat Ini",
        "cost_detail_derived_rate_label": "Harga dari Detail",
        "cost_detail_difference_label": "Selisih",
        "cost_detail_status_label": "Status",
        "cost_detail_apply_earthworks": "Terapkan Harga Detail Earthworks",
        "cost_detail_apply_foundation": "Terapkan Harga Detail Foundation",
        "cost_detail_apply_structural": "Terapkan Harga Detail Structural",
        "cost_detail_apply_architectural": "Terapkan Harga Detail Architectural",
        "cost_detail_apply_consultancy": "Terapkan Harga Detail Consultancy",
        "cost_detail_apply_ffe": "Terapkan Harga Detail FF&E",
        "cost_detail_apply_mep": "Terapkan Harga Detail MEP",
        "cost_detail_apply_utility": "Terapkan Harga Detail Utility",
        "cost_detail_apply_success": "Harga detail {section} diterapkan.",
        "cost_detail_apply_cloud_failed": "Harga detail {section} diterapkan secara lokal, tetapi gagal menyimpan ke cloud. Jangan logout dulu.",
        "cost_detail_apply_no_rate": "Tidak ada harga detail yang valid untuk {section}.",
        "cost_detail_diff_warning": "Harga dari detail {section} berbeda dari harga {section} saat ini di Analisis Biaya. Analisis Biaya belum diperbarui otomatis.",
        "cost_detail_info_title": "Tinjauan Harga dari Detail {section}",
        "admin.feasibility_study": "Studi Kelayakan",
        "admin.loaded_file_ready": "**{name}** sedang dimuat (Anda dapat mulai menghitung proyek)",
        "admin.previous_page": "Kembali",
        "admin.welcome_start": (
            "**Selamat datang di Project Feasibility Study - Agung Sedayu Group**\n\n"
            "Untuk mulai menghitung, buat proyek baru dengan tombol di bawah."
        ),
        "admin.create_new_study": "Buat Studi Baru",
        "admin.create_new_feasibility_study": "Buat Studi Kelayakan Baru",
        "admin.create_study_caption": "Masukkan nama studi. Proyek default baru akan dibuat otomatis.",
        "admin.back": "Kembali",
        "admin.feasibility_study_name": "Nama Studi Kelayakan",
        "admin.study_name_placeholder": "contoh: Project X - Option 1 - Rev 0",
        "admin.enter_study_name": "Masukkan nama studi kelayakan.",
        "admin.duplicate_study_name": "Studi dengan nama ini sudah ada. Gunakan nama lain.",
        "admin.initial_archive_failed": (
            "Studi **{name}** dibuat di sesi saat ini, tetapi arsip awal tidak dapat dibuat."
        ),
        "admin.study_created_saved": "Studi **{name}** berhasil dibuat dan disimpan ke arsip.",
        "admin.study_saved": "Studi **{name}** berhasil disimpan ke arsip.",
        "admin.save_current_page_first": "Simpan halaman saat ini terlebih dahulu jika diperlukan.",
        "admin.no_saved_studies": "Belum ada studi kelayakan tersimpan.",
        "admin.currently_loaded_file": "File sedang dimuat",
        "admin.saved_at": "Disimpan: {time}{active}",
        "admin.saved_file": "File tersimpan{active}",
        "admin.load": "Muat",
        "admin.loaded_file": "**{name}** berhasil dimuat.",
        "admin.page_count": "Halaman {current} dari {total}",
        "admin.archive": "Arsip",
        "admin.online_backup": "Backup Online",
        "admin.offline_backup": "Backup Offline",
        "admin.notes": "Catatan",
        "admin.project_history": "Riwayat Proyek",
        "admin.working_copy": "Working copy: {name}",
        "admin.legacy_restore_points": "Restore point lama dalam proyek terdeteksi. Restore point baru disimpan secara eksternal.",
        "admin.save_draft": "Simpan Draft",
        "admin.draft_saved": "Draft berhasil disimpan ke cloud.",
        "admin.draft_save_failed": "Draft berubah secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "admin.create_restore_point": "Buat Restore Point",
        "admin.restore_points_used": "{used} dari {limit} restore point terpakai.",
        "admin.restore_point_note": "Catatan restore point",
        "admin.restore_point_note_placeholder": "contoh: Review QS sebelum perubahan VE",
        "admin.restore_point_limit": "Batas restore point tercapai. Hapus restore point lama sebelum membuat yang baru.",
        "admin.restore_point_created": "Restore point {label} berhasil dibuat.",
        "admin.no_restore_points": "Belum ada restore point. Buat satu sebelum melakukan perubahan berisiko.",
        "admin.restore_points": "Restore Points",
        "admin.restore_selected_restore_point": "Pulihkan Restore Point Terpilih",
        "admin.select_restore_point": "Pilih restore point",
        "admin.restore_confirm": "Saya memahami bahwa ini akan mengganti working copy saat ini.",
        "admin.restore_saved": "Restore point terpilih berhasil disimpan ke working copy.",
        "admin.restore_save_failed": "Restore point dipulihkan secara lokal, tetapi gagal disimpan ke cloud. Jangan logout dulu.",
        "admin.restore_failed": "Restore point terpilih tidak dapat dipulihkan.",
        "admin.compare_current_restore": "Bandingkan Saat Ini vs Restore Point",
        "admin.select_restore_compare": "Pilih restore point untuk dibandingkan",
        "admin.no_restorable_snapshot": "Restore point terpilih tidak memiliki snapshot yang dapat dipulihkan.",
        "admin.delete_restore_point": "Hapus Restore Point",
        "admin.select_restore_delete": "Pilih restore point untuk dihapus",
        "admin.delete_restore_confirm": "Saya memahami bahwa ini hanya akan menghapus restore point ini secara permanen.",
        "admin.restore_point_deleted": "Restore point berhasil dihapus.",
        "admin.label": "Label",
        "admin.note": "Catatan",
        "admin.created_at": "Dibuat Pada",
        "admin.created_by": "Dibuat Oleh",
        "admin.current": "Saat Ini",
        "admin.restore_point": "Restore Point",
        "admin.change": "Perubahan",
        "admin.write_note": "Tulis catatan",
        "admin.note_placeholder": "Contoh: Cek area lanskap dan rate nanti...",
        "admin.add_note": "Tambah Catatan",
        "admin.write_note_first": "Tulis catatan terlebih dahulu.",
        "admin.add_simple_note": "Tambah Catatan Sederhana",
        "admin.saved_notes": "Catatan Tersimpan",
        "admin.no_notes": "Belum ada catatan.",
        "admin.delete_simple_note": "Hapus Catatan Sederhana",
        "admin.name": "Nama",
        "admin.project_name_required": "Masukkan nama proyek.",
        "admin.save": "Simpan",
        "admin.load_file": "Muat File",
        "admin.no_saved_projects": "Belum ada proyek tersimpan.",
        "admin.showing_saved_files": "Menampilkan {start}-{end} dari {total} file tersimpan",
        "admin.rename": "Ubah Nama",
        "admin.new_file_name": "Nama file baru",
        "admin.save_name": "Simpan Nama",
        "admin.file_renamed": "Nama file berhasil diubah.",
        "admin.delete_file_confirm": "Hapus **{name}**?",
        "admin.archived_file_removed": "File arsip ini akan dihapus dari daftar.",
        "admin.file_deleted": "File berhasil dihapus.",
        "admin.previous": "Sebelumnya",
        "admin.next": "Berikutnya",
    },
}
